language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
services:
    - mongodb
    - rabbitmq
    - redis-server
#addons:
    #postgresql: "9.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y beanstalkd
    - echo "START=yes" | sudo tee -a /etc/default/beanstalkd > /dev/null
    - sudo service beanstalkd start
install:
    - pip install --allow-all-external -e .[all,test]
script:
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
